title:              Code Isn't Static
email:              sneha@superluminal.tech
description:        The Life of a Software Developer
author:             Sneha Mahapatra
baseurl:            "/sneha-mahapatra"
url:                "https://sneha-mahapatra.github.io"

# Social Profiles
twitter_username:   
github_username:    sne21star
facebook_username:  
instagram_username:  snehas_tea_shop
linkedin_username:  sneha-mahapatra

# Add your google-analytics ID here to activate google analytics
google_analytics:   # out your google-analytics code

# Build settings
markdown:           kramdown
plugins:
  - jekyll-feed
  - jekyll-paginate-v2
  - jekyll-sitemap ## Uncomment this line to silently generate a sitemaps.org compliant sitemap for your Jekyll site

exclude:
  - Gemfile
  - Gemfile.lock

pagination:
  enabled: true
  per_page: 2
  permalink: '/page/:num/'
  title: ' - page :num'
  limit: 0
  sort_field: 'date'
  sort_reverse: true